### ISSUE TITLE
Option to install default drop rule per switch

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#114]
It would be nice if FSFW could install default drop rules for switch platforms that don't currently drop unmatched traffic by default.  It would also be nice if this was an option that was configurable per switch defined in the `fsfw.xml` config file.

**Comment by ajragusa** [comment]
This should be fairly simple to complete.  Issue 11111 is tracking this in the globalnoc system

**Comment by gth828r** [comment]
I wanted to add emphasis that this definitely needs to be on a **per-switch** basis for the GENI use case.  It turns out that some of the switches we have in GENI do not respect priorities, so installing a drop rule might result in either vendor-specific or non-deterministic behavior in the case of overlapping flows.  I think that probably lines up with what you all are doing anyway in your deployment, since you administratively do default-drop in the switch, but I wanted to mention this issue explicitly.

**Comment by ajragusa** [comment]
Ok thanks for the feature request, we'll try and get to this soon.

**Comment by ajragusa** [comment]
Pull Request #124 should take care of this, additional testing is needed still
