### ISSUE TITLE
OFQueueGetRequest messages not handled properly

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#115]
Looking at the code, it appears that ofp_queue_get_config_requests get handled in `OFControllerChannelHandler.java` by the method `processOFQueueGetRequest`.  I see two issues with the handler:
 * `ofp_queue_get_config_request`  are responded to with `ofp_get_config_reply` instead of `ofp_queue_get_config_reply`
 * The reply is not using the same XID as the request

I am seeing this in the 1.0.5-dev branch.  This is non-critical for GENI, because we haven't exposed queues to our experimenters.

The main issue is that the response will violate the principle of least surprise if someone does send a queue get config message, and it will interact poorly with some OF libraries that handle symmetric messages by keying off of the XID.

**Comment by ajragusa** [comment]
We'll take care of this, its pretty easy to fix.

**Comment by ajragusa** [comment]
in the globalnoc system this is issue 11110

**Comment by ajragusa** [comment]
Brayton is looking at this

**Comment by ajragusa** [comment]
Pull request #122 should take care of this

**Comment by gth828r** [comment]
I think that the issue described in globalnoc issue 11110 was addressed, but that only described half of the issue mentioned here.  The other issue was that OFQueueGetConfigRequests should be responded to by an OFQueueGetConfigReply, according to section 5.3.4 of the OF 1.0 spec.  Can you all address that as well?  I think it should just be a one-line change.

**Comment by ajragusa** [comment]
Ok we will take a look at that

**Comment by ajragusa** [comment]
Ok Pull request #130 should take care of the rest of that
