### ISSUE TITLE
FSFW in tag management mode doesn't strip VLAN tag from flow_removed match

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#121]
If a flow_mod is installed with a match that wildcards the VLAN ID, FSFW will apply the slice's VLAN tag for a given port if tag management is enabled.  If a flow_removed message is generated, the VLAN tag is still present in the match that is returned to the controller.

**Comment by gth828r** [comment]
I think that in practice, this wouldn't bite too many experimenters.  Any platform that does strict checking of flows might end up in a confused state, but I'm personally not sure of which platforms are that strict.  I detected this issue with a modified version of oftest's FlowRemoved test.

**Comment by ajragusa** [comment]
Good catch I'll see if we can put this in 1.0.5

**Comment by ajragusa** [comment]
ok pull request #125 should take care of this

**Comment by ajragusa** [comment]
I noticed a problem with this commit... re-opening

**Comment by ajragusa** [comment]
OK #126 should fix all of this

**Comment by gth828r** [comment]
This issue is still partially present.  When I run my test to see if a flow_removed message returns the same flow that was used in managed tag mode, the VLAN tag is now zeroed out, but the wildcard value for the dl_vlan in the match is not set.  It looks like [line 1001] (https://github.com/GlobalNOC/FlowSpaceFirewall/blob/88f3f1f32cdb7b2a6a0257f3822a6865e5cafbdc/src/main/java/edu/iu/grnoc/flowspace_firewall/Proxy.java#L1001) attempts to set the wildcard bit, but in testing it seems like it isn't taking place.

Perhaps the `setWildcards()` method needs to be used instead, similar to how it is called in [Line 688](https://github.com/GlobalNOC/FlowSpaceFirewall/blob/88f3f1f32cdb7b2a6a0257f3822a6865e5cafbdc/src/main/java/edu/iu/grnoc/flowspace_firewall/Proxy.java#L688)?

**Comment by gth828r** [comment]
I'd like to run my tests with this bug fixed, so I'm going to fix it up locally.  I'll submit a PR with a fix for this based off of master.
