### ISSUE TITLE
Log level for managed tag mode packet out ALL port expansion case message incorrect

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#135]
I think that one of the changes that @thompsbp made in 89bab597840270169cb06e0912132a9b6bd31e23 was lost along the way.  In particlar, VLANSlicer.java line 456 in both [master] (https://github.com/GlobalNOC/FlowSpaceFirewall/blob/master/src/main/java/edu/iu/grnoc/flowspace_firewall/VLANSlicer.java#L456) and [1.0.5-dev] (https://github.com/GlobalNOC/FlowSpaceFirewall/blob/1.0.5-dev/src/main/java/edu/iu/grnoc/flowspace_firewall/VLANSlicer.java#L456) currently are set to log at the error level, whereas 89bab597840270169cb06e0912132a9b6bd31e23 has a change to that message to be at the debug level, which makes more sense to me.  Currently, I am seeing many entries in my log that look like this:
```
ERROR [e.i.g.f.VLANSlicer] Packet Out Action: OUTPUT
```

**Comment by ajragusa** [comment]
Ok we'll take a look and fix, thanks for reporting it
