### ISSUE TITLE
Switch flow stats polling rate should be configurable

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#48]
Flowspace firewall currently polls the downstream device for flow stats at a rate of once every ten seconds.  It would be nice if the rate at which flow stats requests were sent out was configurable.  Some controlled environments with specific applications and high end switches might want to query more quickly, while other environments might benefit from having a slower polling rate.

**Comment by ajragusa** [comment]
this is issue 11112 in the globalnoc system

**Comment by ajragusa** [comment]
Pull request #129 should take care of this
