### ISSUE TITLE
GET_CONFIG_REPLY should have same xid as GET_CONFIG_REQUEST

### ISSUE THREAD

**Issue by gth828r** [GlobalNOC/FlowSpaceFirewall#83]
OFControllerChannelHandler.java has a method `processOFConfigRequest` that directly handles GET_CONFIG_REQUEST messages from the controller.  That method constructs the GET_CONFIG_REPLY.

The GET_CONFIG_REPLY should have the same transaction ID as the request, but the transaction ID is never set in the `processOFConfigRequest` method.  Controllers that expect a response **think** that it never arrives, since the message that does arrive doesn't have a matching transaction ID.

**Comment by ajragusa** [comment]
Thanks for the report, we'll take a look for the 1.0.3 release

**Comment by gth828r** [comment]
Hi, it looks like this hasn't been fixed yet, but you all have moved onto the 1.0.4 release.   Do you all use these github issues in your development workflow, or would it be better if I reported this somewhere else, like the GRNOC ticketing system?

**Comment by ajragusa** [comment]
We did not have a chance to get to this in the previous releases.  I have a ticket tracking this in our system (10926) and soon we will have better integration between github and our systems.

**Comment by ajragusa** [comment]
This is fixed in the 1.0.5-dev branch and will be released as part of 1.0.5

**Comment by gth828r** [comment]
The change looks good to me, thanks!  I'll be sure to test it out when 1.0.5 gets released.
